<?php

namespace App\Repository;

use App\Entity\MovimientoDetalle;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoDetalleRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, MovimientoDetalle::class);
    }

    public function nuevoFacturaDetalle($arrSeleccionados)
    {
        $em = $this->getEntityManager();
        $strRespuesta = "";
        if (count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados as $codigoMovimientoDetalle) {

            }
        }
    }

    public function eliminar($arrSeleccionados)
    {
        $em = $this->getEntityManager();
        $strRespuesta = "";
        if (count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados as $codigoMovimientoDetalle) {
                $arMovimientoDetalle = $em->getRepository("App:MovimientoDetalle")->find($codigoMovimientoDetalle);
                $em->remove($arMovimientoDetalle);
            }
        }
        return $strRespuesta;
    }
}