<?php

namespace App\Repository;

/**
 * MovimientoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
