<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends EntityRepository {

    public function eliminar($arrSeleccionados) {
        $em = $this->getEntityManager();
        $strRespuesta = "";
        if (count($arrSeleccionados) > 0) {
            foreach ($arrSeleccionados as $codigoMovimiento) {
                $arMovimiento = $em->getRepository('App:Movimiento')->find($codigoMovimiento);
                $arMovimientoDetalle = $em->getRepository('App:MovimientoDetalle')->findBy(array('codigoMovimientoFk' => $codigoMovimiento));
                if (!$arMovimientoDetalle) {
                    $em->remove($arMovimiento);
                } else {
                    $strRespuesta = "El movimiento " . $arMovimiento->getCodigoMovimientoPk() . " tiene registros asociados";
                }
            }
            $em->flush();
        }
        return $strRespuesta;
    }

}
