<?php

namespace App\Repository;

use App\Funciones;
use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoRepository extends EntityRepository
{

    public function eliminar($arrSeleccionados)
    {
        $objFuncion = new Funciones();
        $em = $this->getEntityManager();
        if ($arrSeleccionados) {
            try {
                foreach ($arrSeleccionados as $codigoMovimiento) {
                    $arMovimiento = $em->getRepository('App:Movimiento')->find($codigoMovimiento);
                    $em->remove($arMovimiento);
                }
                $em->flush();
            } catch (\Exception $exception) {
                $objFuncion->Mensaje("error", "No se puede eliminar el registro, se esta utilizando en el sistema.");
            }
        }
    }

}
