<?php

namespace App\Repository;

/**
 * TerceroTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerceroTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
